name: CI

on:
  push:
    branches:
      - PREP
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04-large

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=testdb" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Build the web container
        run: docker compose build

      - name: start web container only
        run: docker compose up -d web

      - name: Run tests
        run: docker compose exec web python manage.py showmigrations

      - name: Teardown containers
        run: docker compose down

