name: CI

on:
  push:
    branches:
      - PREP
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=testdb" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Build and run containers with Docker Compose
        run: docker compose up -d --build

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for Postgres...";
            sleep 3;
          done

      - name: Run tests
        run: docker compose exec web python manage.py test

      - name: Teardown containers
        run: docker compose down

